
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fauzanlh 10118227_FauzanLukmanulHakim_IF6
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        txtBil1.setVisible(false);
        txtOps.setVisible(false);
        txtBil2.setVisible(false);
        txtJumlah.setVisible(false);
        txtSimpan.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHasil = new javax.swing.JTextField();
        btnTujuh = new javax.swing.JButton();
        btnDelapan = new javax.swing.JButton();
        btnSembilan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEmpat = new javax.swing.JButton();
        btnLima = new javax.swing.JButton();
        btnEnam = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        btnSamaDengan = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnSatu = new javax.swing.JButton();
        btnDua = new javax.swing.JButton();
        btnTiga = new javax.swing.JButton();
        txtJudul = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        txtBil1 = new javax.swing.JLabel();
        txtOps = new javax.swing.JLabel();
        txtBil2 = new javax.swing.JLabel();
        txtSimpan = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnTujuh.setText("7");
        btnTujuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTujuhMouseClicked(evt);
            }
        });

        btnDelapan.setText("8");
        btnDelapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelapanMouseClicked(evt);
            }
        });

        btnSembilan.setText("9");
        btnSembilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSembilanMouseClicked(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(33, 32));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        btnEmpat.setText("4");
        btnEmpat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpatMouseClicked(evt);
            }
        });

        btnLima.setText("5");
        btnLima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimaMouseClicked(evt);
            }
        });

        btnEnam.setText("6");
        btnEnam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnamMouseClicked(evt);
            }
        });

        btnKoma.setText(".");
        btnKoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKomaMouseClicked(evt);
            }
        });

        btnSamaDengan.setText("=");
        btnSamaDengan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSamaDenganMouseClicked(evt);
            }
        });

        btnKosong.setText("0");
        btnKosong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKosongMouseClicked(evt);
            }
        });

        btnSatu.setText("1");
        btnSatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSatuMouseClicked(evt);
            }
        });

        btnDua.setText("2");
        btnDua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDuaMouseClicked(evt);
            }
        });

        btnTiga.setText("3");
        btnTiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTigaMouseClicked(evt);
            }
        });

        txtJudul.setText("KALKULATOR DUA BUAH BILANGAN");

        btnClear.setText("C");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnPlusMinus.setText("+ / -");
        btnPlusMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMinusMouseClicked(evt);
            }
        });

        btnTambah.setText("+");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        btnKurang.setText("-");
        btnKurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKurangMouseClicked(evt);
            }
        });

        btnKali.setText("X");
        btnKali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaliMouseClicked(evt);
            }
        });

        btnBagi.setText("/");
        btnBagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagiMouseClicked(evt);
            }
        });

        txtBil1.setText("Bil1");

        txtOps.setText("Ops");

        txtBil2.setText("Bil2");

        txtJumlah.setText("Hasil :");

        jLabel1.setText("FAUZAN LUKMANUL HAKIM - 10118227 - IF6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtBil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBil2)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHasil)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnDua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(5, 5, 5)
                                                .addComponent(btnSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(76, 76, 76)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtJudul)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBil1)
                                .addComponent(txtOps)
                                .addComponent(txtBil2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLima, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSamaDengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtJumlah))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtHasil.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnKomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKomaMouseClicked
        // TODO add your handling code here:
        String Koma = btnKoma.getText();
        txtHasil.setText(txtHasil.getText() + Koma);
    }//GEN-LAST:event_btnKomaMouseClicked

    private void btnKosongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKosongMouseClicked
        // TODO add your handling code here:
        String Nol = btnKosong.getText();
        txtHasil.setText(txtHasil.getText() + Nol);
    }//GEN-LAST:event_btnKosongMouseClicked

    private void btnSatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSatuMouseClicked
        // TODO add your handling code here:
        String Satu = btnSatu.getText();
        txtHasil.setText(txtHasil.getText() + Satu);
    }//GEN-LAST:event_btnSatuMouseClicked

    private void btnDuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDuaMouseClicked
        // TODO add your handling code here:
        String Dua = btnDua.getText();
        txtHasil.setText(txtHasil.getText() + Dua);
    }//GEN-LAST:event_btnDuaMouseClicked

    private void btnTigaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTigaMouseClicked
        // TODO add your handling code here:
        String Tiga = btnTiga.getText();
        txtHasil.setText(txtHasil.getText() + Tiga);
    }//GEN-LAST:event_btnTigaMouseClicked

    private void btnEmpatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpatMouseClicked
        // TODO add your handling code here:
        String Empat = btnEmpat.getText();
        txtHasil.setText(txtHasil.getText() + Empat);
    }//GEN-LAST:event_btnEmpatMouseClicked

    private void btnEnamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnamMouseClicked
        // TODO add your handling code here:
        String Enam = btnEnam.getText();
        txtHasil.setText(txtHasil.getText() + Enam);
    }//GEN-LAST:event_btnEnamMouseClicked

    private void btnTujuhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTujuhMouseClicked
        // TODO add your handling code here:
        String Tujuh = btnTujuh.getText();
        txtHasil.setText(txtHasil.getText() + Tujuh);
    }//GEN-LAST:event_btnTujuhMouseClicked

    private void btnDelapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelapanMouseClicked
        // TODO add your handling code here:
        String Delapan = btnDelapan.getText();
        txtHasil.setText(txtHasil.getText() + Delapan);
    }//GEN-LAST:event_btnDelapanMouseClicked

    private void btnSembilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSembilanMouseClicked
        // TODO add your handling code here:
        String sembilan = btnSembilan.getText();
        txtHasil.setText(txtHasil.getText() + sembilan);
    }//GEN-LAST:event_btnSembilanMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        String Isi = txtHasil.getText();
        if (Isi.length() > 0) {
            txtHasil.setText(Isi.substring(0, Isi.length() - 1));
        } else if (Isi.length() == 0) {
            txtHasil.setText("");
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtHasil.setText("");
        txtHasil.requestFocus();
        txtBil1.setVisible(false);
        txtOps.setVisible(false);
        txtBil2.setVisible(false);
        txtBil1.setText("Bil1");
        txtOps.setText("Ops");
        txtBil2.setText("Bil2");

        txtJumlah.setVisible(false);
        txtHasil.setEditable(true);
        txtHasil.setEditable(true);
        btnKosong.setEnabled(true);
        btnSatu.setEnabled(true);
        btnDua.setEnabled(true);
        btnTiga.setEnabled(true);
        btnEmpat.setEnabled(true);
        btnLima.setEnabled(true);
        btnEnam.setEnabled(true);
        btnTujuh.setEnabled(true);
        btnDelapan.setEnabled(true);
        btnSembilan.setEnabled(true);
        btnKoma.setEnabled(true);
        btnSamaDengan.setEnabled(true);
        btnPlusMinus.setEnabled(true);
        btnKali.setEnabled(true);
        btnKurang.setEnabled(true);
        btnTambah.setEnabled(true);
        btnBagi.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnPlusMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMinusMouseClicked
        String Isi = txtHasil.getText();
        char Ops = 0;
        if (Isi.isEmpty()) {
            txtHasil.setText(" ");
            txtHasil.requestFocus();
            Ops = txtHasil.getText().charAt(0);
            txtHasil.setText(txtHasil.getText().substring(0, txtHasil.getText().length() - 1));
        }
        if (txtHasil.getText().equals("")) {
            txtHasil.setText("-");
        } else if (Isi.charAt(0) == '-' && Isi.length() > 1) {
            //minus ke positif
            txtSimpan.setText(txtHasil.getText());
            String[] pisah = txtSimpan.getText().split("-");
            txtHasil.setText("" + pisah[1]);
        } else if (Isi.charAt(0) != '-') {
            // Positif ke minus
            txtSimpan.setText(txtHasil.getText());
            txtHasil.setText("-" + txtSimpan.getText());
        } else {
            txtSimpan.setText(txtHasil.getText());
            txtHasil.setText("");
        }
    }//GEN-LAST:event_btnPlusMinusMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        if (txtHasil.getText().length() > 0) {
            txtOps.setText("+");
            txtOps.setVisible(true);
            txtBil1.setVisible(true);
            txtBil1.setText(txtHasil.getText());
            txtHasil.setText("");
            txtHasil.requestFocus();
        } else if (txtBil1.getText().equals("Bil1")) {
            JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-1 Dahulu");
            txtHasil.requestFocus();
        } else if (!txtBil1.getText().equals("Bil1")) {
            txtOps.setText("+");
            txtOps.setVisible(true);
            txtHasil.setText("");
            txtHasil.requestFocus();
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnKurangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKurangMouseClicked
        // TODO add your handling code here:
        if (txtHasil.getText().length() > 0) {
            txtOps.setText("-");
            txtOps.setVisible(true);
            txtBil1.setVisible(true);
            txtBil1.setText(txtHasil.getText());
            txtHasil.setText("");
            txtHasil.requestFocus();
        } else if (txtBil1.getText().equals("Bil1")) {
            JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-1 Dahulu");
            txtHasil.requestFocus();
        } else if (!txtBil1.getText().equals("Bil1")) {
            txtOps.setText("-");
            txtOps.setVisible(true);
            txtHasil.setText("");
            txtHasil.requestFocus();
        }
    }//GEN-LAST:event_btnKurangMouseClicked

    private void btnKaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaliMouseClicked
        // TODO add your handling code here:
        if (txtHasil.getText().length() > 0) {
            txtOps.setText("X");
            txtOps.setVisible(true);
            txtBil1.setVisible(true);
            txtBil1.setText(txtHasil.getText());
            txtHasil.setText("");
            txtHasil.requestFocus();
        } else if (txtBil1.getText().equals("Bil1")) {
            JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-1 Dahulu");
            txtHasil.requestFocus();
        } else if (!txtBil1.getText().equals("Bil1")) {
            txtOps.setText("X");
            txtOps.setVisible(true);
            txtHasil.setText("");
            txtHasil.requestFocus();
        }
    }//GEN-LAST:event_btnKaliMouseClicked

    private void btnBagiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagiMouseClicked
        // TODO add your handling code here:  \
        if (txtHasil.getText().length() > 0) {
            txtOps.setText("/");
            txtOps.setVisible(true);
            txtBil1.setVisible(true);
            txtBil1.setText(txtHasil.getText());
            txtHasil.setText("");
            txtHasil.requestFocus();
        } else if (txtBil1.getText().equals("Bil1")) {
            JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-1 Dahulu");
            txtHasil.requestFocus();
        } else if (!txtBil1.getText().equals("Bil1")) {
            txtOps.setText("/");
            txtOps.setVisible(true);
            txtHasil.setText("");
            txtHasil.requestFocus();
        }
    }//GEN-LAST:event_btnBagiMouseClicked

    private void btnSamaDenganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSamaDenganMouseClicked
        // TODO add your handling code here:
        String Ops = null;
        Double bil1, bil2;
        if (txtBil1.getText().equals("Bil1") && txtBil2.getText().equals("Bil2") && txtOps.getText().equals("Ops")) {
            do {
                if (txtHasil.getText().length() > 0) {
                    txtHasil.requestFocus();
                    break;
                } else if (txtBil1.getText().equals("Bil1")) {
                    JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-1 Dahulu");
                    txtHasil.requestFocus();
                    break;
                }
            } while (!txtBil2.getText().equals("Bil1"));
        } else if (!txtBil1.getText().equals("Bil1") && txtBil2.getText().equals("Bil2") && !txtOps.getText().equals("Ops") && txtHasil.getText().isEmpty()) {
            do {
                if (txtHasil.getText().length() > 0) {
                    Ops = txtOps.getText();
                    txtBil2.setText(txtHasil.getText());
                    txtBil2.setVisible(true);
                    break;
                }
                JOptionPane.showMessageDialog(null, "Masukkan Bilangan Yang Ke-2");
                txtHasil.requestFocus();
            } while (!txtBil2.getText().equals("Bil2"));

            if (!txtBil2.getText().equals("Bil2")) {
                txtJumlah.setVisible(true);
                bil1 = Double.valueOf(txtBil1.getText());
                bil2 = Double.valueOf(txtBil2.getText());
                if (Ops == "+" && txtBil2.getText().charAt(0) == '-') {
                    txtBil2.setText("(" + txtHasil.getText() + ")");
                    Double Hasil = bil1 + bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "+") {
                    Double Hasil = bil1 + bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "-" && txtBil2.getText().charAt(0) == '-') {
                    txtBil2.setText("(" + txtHasil.getText() + ")");
                    Double Hasil = bil1 - bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "-") {
                    Double Hasil = bil1 - bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "X" && txtBil2.getText().charAt(0) == '-') {
                    txtBil2.setText("(" + txtHasil.getText() + ")");
                    Double Hasil = bil1 * bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "X") {
                    Double Hasil = bil1 * bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "/" && txtBil2.getText().charAt(0) == '-') {
                    txtBil2.setText("(" + txtHasil.getText() + ")");
                    Double Hasil = bil1 / bil2;
                    txtHasil.setText("" + Hasil);
                } else if (Ops == "/") {
                    Double Hasil = bil1 / bil2;
                    txtHasil.setText("" + Hasil);
                }
                txtHasil.setEditable(false);
                btnKosong.setEnabled(false);
                btnSatu.setEnabled(false);
                btnDua.setEnabled(false);
                btnTiga.setEnabled(false);
                btnEmpat.setEnabled(false);
                btnLima.setEnabled(false);
                btnEnam.setEnabled(false);
                btnTujuh.setEnabled(false);
                btnDelapan.setEnabled(false);
                btnSembilan.setEnabled(false);
                btnKoma.setEnabled(false);
                btnSamaDengan.setEnabled(false);
                btnPlusMinus.setEnabled(false);
                btnKali.setEnabled(false);
                btnKurang.setEnabled(false);
                btnTambah.setEnabled(false);
                btnBagi.setEnabled(false);
                btnHapus.setEnabled(false);
            }
            // if (!txtBil1.getText().equals("Bil1") && txtBil2.getText().equals("Bil2") && !txtOps.getText().equals("Ops"))
        } else {
            txtJumlah.setVisible(true);
            Ops = txtOps.getText();
            txtBil2.setText(txtHasil.getText());
            txtBil2.setVisible(true);
            bil1 = Double.valueOf(txtBil1.getText());
            bil2 = Double.valueOf(txtBil2.getText());
            if (Ops == "+" && txtBil2.getText().charAt(0) == '-') {
                txtBil2.setText("(" + txtHasil.getText() + ")");
                Double Hasil = bil1 + bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "+") {
                Double Hasil = bil1 + bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "-" && txtBil2.getText().charAt(0) == '-') {
                txtBil2.setText("(" + txtHasil.getText() + ")");
                Double Hasil = bil1 - bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "-") {
                Double Hasil = bil1 - bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "X" && txtBil2.getText().charAt(0) == '-') {
                txtBil2.setText("(" + txtHasil.getText() + ")");
                Double Hasil = bil1 * bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "X") {
                Double Hasil = bil1 * bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "/" && txtBil2.getText().charAt(0) == '-') {
                txtBil2.setText("(" + txtHasil.getText() + ")");
                Double Hasil = bil1 / bil2;
                txtHasil.setText("" + Hasil);
            } else if (Ops == "/") {
                Double Hasil = bil1 / bil2;
                txtHasil.setText("" + Hasil);
            }
            txtHasil.setEditable(false);
            btnKosong.setEnabled(false);
            btnSatu.setEnabled(false);
            btnDua.setEnabled(false);
            btnTiga.setEnabled(false);
            btnEmpat.setEnabled(false);
            btnLima.setEnabled(false);
            btnEnam.setEnabled(false);
            btnTujuh.setEnabled(false);
            btnDelapan.setEnabled(false);
            btnSembilan.setEnabled(false);
            btnKoma.setEnabled(false);
            btnSamaDengan.setEnabled(false);
            btnPlusMinus.setEnabled(false);
            btnKali.setEnabled(false);
            btnKurang.setEnabled(false);
            btnTambah.setEnabled(false);
            btnBagi.setEnabled(false);
            btnHapus.setEnabled(false);
        }

    }//GEN-LAST:event_btnSamaDenganMouseClicked

    private void btnLimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimaMouseClicked
        // TODO add your handling code here:
        String Lima = btnLima.getText();
        txtHasil.setText(txtHasil.getText() + Lima);
    }//GEN-LAST:event_btnLimaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelapan;
    private javax.swing.JButton btnDua;
    private javax.swing.JButton btnEmpat;
    private javax.swing.JButton btnEnam;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnLima;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSamaDengan;
    private javax.swing.JButton btnSatu;
    private javax.swing.JButton btnSembilan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTiga;
    private javax.swing.JButton btnTujuh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtBil1;
    private javax.swing.JLabel txtBil2;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtJumlah;
    private javax.swing.JLabel txtOps;
    private javax.swing.JLabel txtSimpan;
    // End of variables declaration//GEN-END:variables
}
